[build-system]
requires = ["scikit-build-core", "pybind11", "setuptools_scm"]
build-backend = "scikit_build_core.build"

[project]
name = "lll-gas-corr-lib"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "h5py",
]

[project.optional-dependencies]
test = [
	"pytest",
	"pyhdf",
	"matplotlib",
	"netCDF4",
]

[tool.scikit-build]
cmake.source-dir = "gas_corrections_lib/gas_corrections_cpp"
wheel.packages = ["gas_corrections_lib"]
wheel.exclude = [
    "**/*.cpp",
    "**/*.hpp",
    "**/*.h",
    "**/__pycache__/**",
    "**/.pytest_cache/**",
]

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.setuptools_scm"

[tool.cibuildwheel]
build = "cp*"  # Wheels will be built for all CPython versions subject to the versions specified by requires-python
skip = "*-win* *-musllinux*"  # Exclude Windows and Alpine/musl Linux (leaving only macOS and manylinux)
test-requires = ["pytest", "pyhdf", "netCDF4"]
test-command = "pytest {project}/gas_corrections_lib/test"
build-verbosity = 1

[tool.cibuildwheel.linux]
before-all = "yum install -y epel-release && yum install -y hdf-devel"

[tool.cibuildwheel.macos]
before-all = """
brew update
brew tap osgeo/osgeo4mac;
brew trust --formula osgeo/osgeo4mac/osgeo-hdf4;
brew install osgeo-hdf4;
"""
