name: Build wheels

on:
  workflow_dispatch:  # Allows for manual triggering of this action through the GitHub interface
  push:
    tags:
      - 'v*'     # CI will only rebuild when a new version tag (prefixed with v) is pushed

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Fetches full history + tags, necessary because setuptools_scm uses version number when creating wheel name
          
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: git lfs pull

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.2.0
        env:
          CIBW_DEBUG_KEEP_CONTAINER: "1"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

      - name: Setup interactive SSH debugging session
        if: ${{ failure() }} # Only runs if the step above fails
        uses: mxschmitt/action-tmate@v3
        with:
          # Restrict access to the user who triggered the workflow for security
          limit-access-to-actor: true 
