name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: lfs-${{ hashFiles('.lfs-assets-id') }}

      - run: git lfs pull

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo sed -i 's|azure.archive.ubuntu.com|archive.ubuntu.com|g' /etc/apt/sources.list.d/*.sources 2>/dev/null || true  # Azure mirror for libHDF4 doesn't exist, force plain mirror instead to prevent lengthy retries.
          sudo apt-get update
          sudo apt-get install -y libhdf4-dev

      - run: pip install -e ".[test]"
      - run: pytest gas_corrections_lib/test
